### PR TITLE
Add options to make metrics easier to use when not instrumenting code

### PR DESCRIPTION
**Pull request by aintgoin2goa**

### CODE REVIEW

**Comment by aintgoin2goa** [comment]
@commuterjoy  @matthew-andrews

**Comment by commuterjoy** [comment]
What sort of metrics would collect that aren't part of a running application on heroku?

**Comment by aintgoin2goa** [comment]
From my syslog server.  It is running on heroku but I need to send the metrics I get from the log messages.

**Comment by commuterjoy** [comment]
Can that not follow the same convention - platform.app.instance.metric? It keeps everything neat and tidy and obvious about where the metrics are emanating.

**Comment by aintgoin2goa** [comment]
It will.  The metrics will be collected as ft.access.metric what I need is to break the link between the metric name and the currently running app.  The syslog app will need to collect metrics about itself too, but with the traditional namespacing

**Comment by commuterjoy** [comment]
Do you need next-metrics at all then?

I was mostly designed as a means to proxy node library methods in a standard way across apps.

For ad-hoc things I'd just do something like this :-

https://github.com/Financial-Times/next-fastly-to-graphite/tree/master/lib/graphite

M

**Comment by aintgoin2goa** [comment]
*cough*

**Pull request closed without merging**
