### PR TITLE
Added v3 mget service

### PR DESCRIPTION
**Pull request by wheresrhys**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
i think this should be covered by the item ones……

**Comment by matthew-andrews** [comment]
ah, no i mean, i think all calls to `_mget` should be via `/item/_mget`

**Comment by matthew-andrews** [comment]
no! 

`/^https?:\/\/[\w\-]+\.[\w\-]+\.es\.amazonaws\.com\/v3_api_v2\/item` should be fine for both…

how does this not break next-express… surely can't redefine the same keys??

**Comment by wheresrhys** [comment]
I released a patch on master about 30s after realising my mistake with this

**Comment by matthew-andrews** [comment]
ah lovely jubbly

**Comment by wheresrhys** [comment]
but js is surprisingly forgiving of repeated keys. e.g. the tests in service registry have to jump through hoops to test for non-repetition http://git.svc.ft.com:8080/projects/NEXT/repos/service-registry/browse/test/profile.js#58

**Comment by matthew-andrews** [comment]
hmm…… that test is for an array of objects… a bit different i think

**Comment by wheresrhys** [comment]
hmmm, maybe not those tests then, but anyway `{a: 'a', a: 'b'}` is fine


On 23 November 2015 at 13:08, Matt Andrews <notifications@github.com> wrote:

> hmm…… that test is for an array of objects… a bit different i think
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/next-metrics/pull/64#issuecomment-158929264>
> .
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by matthew-andrews** [comment]
eslint shoudl catch it i think………

**Pull request merged**
