### PR TITLE
Add 3playmedia service to the registry

### PR DESCRIPTION
**Pull request by HelenHTech**

### CODE REVIEW

**Comment by HelenHTech** [comment]
Hey @Financial-Times/cp-reliability, we have used the key `three-play-media`. Can you advise if this value is meant to correlate with anything, or can it just be a reference for us to understand?
cc @rosalie-baxter

**Comment by umbobabo** [comment]
> Hey @Financial-Times/cp-reliability, we have used the key `three-play-media`. Can you advise if this value is meant to correlate with anything, or can it just be a reference for us to understand? cc @rosalie-baxter

Thank you @HelenHTech for the PR.
In the last paragraph of the documentation [here](https://github.com/Financial-Times/next-metrics/blob/6f2ba030dbb3f7de94cf91304c917d84ae488c99/README.md#services) they say that the key for that field should be used only in Graphite to group the metrics. That likely will be surface in Grafana as label in some dashboard.

**Comment by rosalie-baxter** [comment]
> > Hey @Financial-Times/cp-reliability, we have used the key `three-play-media`. Can you advise if this value is meant to correlate with anything, or can it just be a reference for us to understand? cc @rosalie-baxter
> 
> Thank you @HelenHTech for the PR. In the last paragraph of the documentation [here](https://github.com/Financial-Times/next-metrics/blob/6f2ba030dbb3f7de94cf91304c917d84ae488c99/README.md#services) they say that the key for that field should be used only in Graphite to group the metrics. That likely will be surface in Grafana as label in some dashboard.

heya 👋 thanks for this! So our understanding is that it doesn't need to directly correlate with something which exists as it's just a reference for them to group the api calls by @umbobabo?

**Comment by umbobabo** [comment]
> > > Hey @Financial-Times/cp-reliability, we have used the key `three-play-media`. Can you advise if this value is meant to correlate with anything, or can it just be a reference for us to understand? cc @rosalie-baxter
> > 
> > 
> > Thank you @HelenHTech for the PR. In the last paragraph of the documentation [here](https://github.com/Financial-Times/next-metrics/blob/6f2ba030dbb3f7de94cf91304c917d84ae488c99/README.md#services) they say that the key for that field should be used only in Graphite to group the metrics. That likely will be surface in Grafana as label in some dashboard.
> 
> heya 👋 thanks for this! So our understanding is that it doesn't need to directly correlate with something which exists as it's just a reference for them to group the api calls by @umbobabo?

Correct

**Review by umbobabo — APPROVED** [review]

**Pull request merged**
